export const results = [
  {
    id: 0,
    type: 'hospital',
    title: 'Sikhadevi Hospital',
    subtitle: null,
    image: 'https://picsum.photos/200/300',
    minCharge: 500,
    timing: '9:00 AM to 10:00 PM',
    location: 'Gandhi Nagar, Delhi',
    stars: 4,
    maxStars: 5,
    available: true,
    currencyCode: 'INR',
  },
  {
    id: 1,
    type: 'doctor',
    title: 'Dr. Priyambada Nayak',
    subtitle: 'MBBS Doctor, Professional',
    image: 'https://picsum.photos/201/301',
    minCharge: 500,
    timing: '9:00 AM to 10:00 PM',
    location: 'Gandhi Nagar, Delhi',
    stars: 4.5,
    maxStars: 5,
    available: true,
    currencyCode: 'USD',
  },
  {
    id: 2,
    type: 'doctor',
    title: 'Dr. Mahesh Tripathy',
    subtitle: 'Neurologist, SUM',
    image: 'https://picsum.photos/202/302',
    minCharge: 15000,
    timing: '9:00 AM to 10:00 PM',
    location: 'Gandhi Nagar, Delhi',
    stars: 4.5,
    maxStars: 5,
    available: true,
    currencyCode: 'INR',
  },
  {
    id: 3,
    type: 'doctor',
    title: 'Dr. Anand Chanchalani',
    subtitle: 'BDS Doctor, Dental',
    image: 'https://picsum.photos/203/303',
    minCharge: 5000,
    timing: '9:00 AM to 10:00 PM',
    location: 'Qutab Minar, Agra',
    stars: 4.5,
    maxStars: 5,
    available: true,
    currencyCode: 'EUR',
  },
  {
    id: 4,
    type: 'hospital',
    title: 'Sunshine Hospital',
    subtitle: null,
    image: 'https://picsum.photos/204/304',
    minCharge: 1500,
    timing: '9:00 AM to 10:00 PM',
    location: 'Kanyakumari, Tamil Nadu',
    stars: 4.5,
    maxStars: 5,
    available: true,
    currencyCode: 'EUR',
  },
  {
    id: 5,
    type: 'hospital',
    title: 'Revolution Healthcare',
    subtitle: 'Cutting edge cancer therapy',
    image: 'https://picsum.photos/205/305',
    minCharge: 150000,
    timing: '9:00 AM to 10:00 PM',
    location: 'Near AIIMS, Bhubaneswar',
    stars: 4.5,
    maxStars: 5,
    available: true,
    currencyCode: 'INR',
  },
]

export const hospitaltext = 'Loreto is a city on Mexico’s Baja California Peninsula, on the Gulf of California. Its colonial buildings include the Misión de Nuestra Señora de Loreto, a 17th-century church. Off the coast, the islands and waters of Bahía de Loreto National Park are home to dolphins, whales and pelicans. The city is backed by the Sierra de la Giganta mountain range, where trails lead to prehistoric cave paintings.'