export const results = [
  {
    id: 0,
    type: 'hospital',
    title: 'Sikhadevi Hospital',
    subtitle: null,
    image: 'https://picsum.photos/200/300',
    minCharge: 500,
    timing: '9:00 AM to 10:00 PM',
    location: 'Gandhi Nagar, Delhi',
    stars: 4,
    maxStars: 5,
    available: true,
    currency: 'INR',
  },
  {
    id: 1,
    type: 'doctor',
    title: 'Dr. Priyambada Nayak',
    subtitle: 'MBBS Doctor, Professional',
    image: 'https://picsum.photos/201/301',
    minCharge: 500,
    timing: '9:00 AM to 10:00 PM',
    location: 'Gandhi Nagar, Delhi',
    stars: 4.5,
    maxStars: 5,
    available: true,
    currency: 'INR',
  },
]
